import { CardType } from "./types/card-types";

export const cardSet: CardType[] = [
  {
    id: "foxflame",
    name: "Foxflame Cub",
    image: "/foxflame.webp",
    attack: 1,
    mana: 1,
    element: "fire",
    description: "A fiery little beast with quick paws and quicker flames.",
  },
  {
    id: "shadowgoblin",
    name: "Shadow Goblin",
    image: "/shadowgoblin.webp",
    attack: 1,
    mana: 1,
    element: "dark",
    description: "He steals in silence, strikes in shadows.",
  },
  {
    id: "windshuriken",
    name: "Wind Shuriken",
    image: "/windshuriken.webp",
    attack: 1,
    mana: 1,
    element: "air",
    description: "A rogue ninja’s enchanted throwing blade.",
  },

  {
    id: "emberwolf",
    name: "Ember Wolf",
    image: "/emberwolf.webp",
    attack: 3,
    mana: 2,
    element: "fire",
    description: "Its howls light fires in the hearts of men… and forests.",
  },
  {
    id: "rookieblade",
    name: "Rookie Blade",
    image: "/rookieblade.webp",
    attack: 3,
    mana: 2,
    element: "earth",
    description: "A trainee warrior with something to prove.",
  },
  {
    id: "aquamyst",
    name: "Aquamyst Familiar",
    image: "/aquamyst.webp",
    attack: 3,
    mana: 2,
    element: "water",
    description: "Summoned from the Mist Temple, it flows around water.",
  },

  {
    id: "thornbeast",
    name: "Thornbeast",
    image: "/thornbeast.webp",
    attack: 5,
    mana: 3,
    element: "earth",
    description: "Covered in vines, fueled by rage. Forest's wrath incarnate.",
  },
  {
    id: "bladechant",
    name: "Bladechant Monk",
    image: "/bladechant.webp",
    attack: 5,
    mana: 3,
    element: "light",
    description: "Each slash is a prayer, each prayer a wound.",
  },

  {
    id: "stormninja",
    name: "Storm Ninja",
    image: "/stormninja.webp",
    attack: 7,
    mana: 4,
    element: "air",
    description: "Strikes like lightning—seen only after it hits.",
  },

  {
    id: "celestialwyrm",
    name: "Celestial Wyrm",
    image: "/celestialwyrm.webp",
    attack: 10,
    mana: 5,
    element: "light",
    description: "Born of starlight, it descends once every 1,000 years.",
  },
];
